import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/component/layout/layoutcomponent";
import ProtectedRoute from "@/component/ProtectedRoute";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>MySchool</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        With these changes, the layout will now: Be fully responsive, showing a
        collapsible sidebar on mobile. Display icons for each menu item in the
        sidebar. Have a smooth transition when opening and closing the sidebar
        on mobile. Ensure that the content area adapts to the sidebar’s presence
        and shifts smoothly when the sidebar is opened on smaller screens.
        Testing: To test this: On a desktop, the sidebar should always be
        visible. On a mobile or small screen, the sidebar should be hidden by
        default and can be opened by clicking the menu button in the AppBar.
        This should now work as expected, with a fully responsive layout. Let me
        know if you have any further questions or issues!
      </ProtectedRoute>
    </>
  );
}
